### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by ghost** [pbi-qfs/ecd#1]
Instructions on how to get from a source-code checkout to having the plugins loaded in your IDE would be useful.

This encourages contributions as well since it makes it easier to get involved.

**Comment by RobertZenz** [comment]
Yes, you're right we are currently missing any form of build instructions and information.

The easiest way should be something like this:

 1. Import all projects into Eclipse.
 2. Open the site.xml from the updatesite project.
 3. Press "Build All"

I mean, we could also add Maven as build system (or Ant with Tycho? But I'm more suspicious of that one than Maven...and I don't like Maven), that would allow to build everything on the invocation of one command.

@pbi-qfs Thoughts?

**Comment by pbi-qfs** [comment]
Since it is an eclipse-plugin, I'm fine with requiring Eclipse to build. I'll add some basic steps to the README.

**Comment by pbi-qfs** [comment]
Fixed by 91f45d1
